# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ListForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(418, 254)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.delallButton = QtWidgets.QPushButton(Form)
        self.delallButton.setMinimumSize(QtCore.QSize(75, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delallButton.setFont(font)
        self.delallButton.setObjectName("delallButton")
        self.gridLayout.addWidget(self.delallButton, 1, 0, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(Form)
        self.cancelButton.setMinimumSize(QtCore.QSize(75, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 1, 1, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setMinimumSize(QtCore.QSize(400, 200))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 0, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.delallButton.setText(_translate("Form", "Удалить все"))
        self.cancelButton.setText(_translate("Form", "Отмена"))
