# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(624, 176)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.dirLabel = QtWidgets.QLabel(self.centralwidget)
        self.dirLabel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.dirLabel.setFont(font)
        self.dirLabel.setObjectName("dirLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dirLabel)
        self.dirLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.dirLineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.dirLineEdit.setObjectName("dirLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dirLineEdit)
        self.wordLabel = QtWidgets.QLabel(self.centralwidget)
        self.wordLabel.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.wordLabel.setFont(font)
        self.wordLabel.setObjectName("wordLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.wordLabel)
        self.wordLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.wordLineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.wordLineEdit.setObjectName("wordLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.wordLineEdit)
        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButton.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SearchButton.setFont(font)
        self.SearchButton.setObjectName("SearchButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.SearchButton)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dirLabel.setText(_translate("MainWindow", "Директория :"))
        self.wordLabel.setText(_translate("MainWindow", "Фраза/слово :"))
        self.SearchButton.setText(_translate("MainWindow", "Найти"))
        self.pushButton.setText(_translate("MainWindow", "справка"))
